### ISSUE TITLE
UnauthorizedError: secret or public key must be provided

### ISSUE THREAD

**Issue by ykuzma1** [ory/kratos-selfservice-ui-node#76] opened 2020-09-16 05:19 UTC
**Describe the bug**

I setup Oathkeeper, Kratos, and the Self Service UI using the [Zero Trust with IAP Proxy](https://www.ory.sh/kratos/docs/guides/zero-trust-iap-proxy-identity-access-proxy/) guide in our testing environment. I am able to login a user using OIDC (as reflected in the Kratos /identities API). But I get an error on the /dashboard page in the Self Service UI. Here's the error log from Self Service UI:

```
UnauthorizedError: secret or public key must be provided
at /usr/src/app/node_modules/express-jwt/lib/index.js:105:22
at /usr/src/app/node_modules/jsonwebtoken/verify.js:106:14
at getSecret (/usr/src/app/node_modules/jsonwebtoken/verify.js:90:14)
at Object.module.exports [as verify] (/usr/src/app/node_modules/jsonwebtoken/verify.js:94:10)
at verifyToken (/usr/src/app/node_modules/express-jwt/lib/index.js:103:13)
at fn (/usr/src/app/node_modules/async/lib/async.js:746:34)
at /usr/src/app/node_modules/async/lib/async.js:1213:16
at /usr/src/app/node_modules/async/lib/async.js:166:37
at /usr/src/app/node_modules/async/lib/async.js:706:43
at /usr/src/app/node_modules/async/lib/async.js:167:37
```

**To Reproduce**

I'm currently struggling to get the quickstart to reproduce the error, but will update this report as soon as I do.

Here is my current config for `kratos-selfservice-ui-node`:

```
HOST=<domain name here>

KRATOS_PUBLIC_URL=http://kratos:4433/
KRATOS_ADMIN_URL=http://kratos:4434/
BASE_URL=https://$HOST
SECURITY_MODE=jwt
JWKS_URL=http://oathkeeper:4456/.well-known/jwks.json
KRATOS_BROWSER_URL=https://$HOST/.ory/kratos/public
```

The error log makes me think it's a problem with the `JWKS_URL` setting, but it appears to be set correctly? I can ping that URL manually just fine.

**Expected behavior**

I expect to see the dashboard like I was able to do locally with the standalone Kratos quickstart.

**Environment**

Oathkeeper: v0.38.3
Kratos: v0.4.6
Self Service UI: v0.4.6

**Comment by aeneasr** [comment] 2020-09-16 09:16
Have you tried the [quickstart.yml for oathkeeper](https://github.com/ory/kratos/blob/master/quickstart-oathkeeper.yml)?

**Comment by ykuzma1** [comment] 2020-09-16 13:02
@aeneasr That's just it - I'm having trouble getting the quickstart.yml for oathkeeper to replicate the "secret or public key must be provided" error. When I do

```
docker-compose -f quickstart.yml -f quickstart-oathkeeper.yml up
```

in a fresh Kratos clone, I run into config errors. To fix those config errors and open up the Self Service UI port, I applied the following patch:

[quickstart.diff.txt](https://github.com/ory/kratos-selfservice-ui-node/files/5232302/quickstart.diff.txt)

Unfortunately, that gives me a completely different error than the one I am experiencing in testing when I open the browser to `http://127.0.0.1:4435/`. It does not prompt me to login, and just show a "No authorization token was found" error instead. Here are the associated logs:

```
UnauthorizedError: No authorization token was found
     at middleware (/usr/src/app/node_modules/express-jwt/lib/index.js:79:21)
     at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
     at next (/usr/src/app/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/usr/src/app/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
     at /usr/src/app/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:335:12)
     at next (/usr/src/app/node_modules/express/lib/router/index.js:275:10)
    at SendStream.error (/usr/src/app/node_modules/serve-static/index.js:121:7)
    at SendStream.emit (events.js:321:20)
```

**Comment by zepatrik** [comment] 2020-09-17 09:28
That error seems to come if you use the current master https://github.com/ory/kratos-selfservice-ui-node/issues/38#issuecomment-694091867
Are you sure you are using the latest releases?

**Comment by ycgambo** [comment] 2020-09-17 10:04
#77 may related

**Comment by aeneasr** [comment] 2020-09-24 09:49
Closing as #77 was closed

**Closed by aeneasr** 2020-09-24 09:49 UTC

**Comment by ykuzma1** [comment] 2020-09-29 14:07
Hey @aeneasr, can this be re-opened? #77 was blocking me from debugging further, but I am still having the issue described in the original issue posted with the `UnauthorizedError`.

As for an update to my issue, I now have the quickstart running on my dev machine as well as the testing instance on a server. The quickstart is working beautifully now (with the mods from #77). However the testing instance is still getting `UnauthorizedError`. I've compared all config settings and they seem to match other than having "real" endpoints now. I'd be happy to debug further, but I'm not sure where. Any ideas?

The most straightforward reading of the error makes me keep thinking `JWKS_URL` is configured wrong but I can manually hit that endpoint (http://oathkeeper:4456/.well-known/jwks.json).

One oddity I noticed - the Kratos selfservice UI /debug endpoint in testing *does* show an expected `Authorization` header as well as the `ory_kratos_session` cookie. So the UI does seem to be processing the auth correctly here, and it seems like it could just be a display issue with the selfservice UI to me?

**Comment by ykuzma1** [comment] 2020-09-29 14:07
The most straightforward reading of the error makes me keep thinking `JWKS_URL` is configured wrong but I can manually hit that endpoint (http://oathkeeper:4456/.well-known/jwks.json).

One oddity I noticed - the Kratos selfservice UI /debug endpoint in testing *does* show an expected `Authorization` header as well as the `ory_kratos_session` cookie. So the UI does seem to be processing the auth correctly here, and it seems like it could just be a display issue with the selfservice UI to me?

**Comment by ykuzma1** [comment] 2020-10-01 13:47
It seems that the verification of the JSON web keys is done in the [`Oathkeeper middleware`](https://github.com/ory/kratos-selfservice-ui-node/blob/master/src/middleware/oathkeeper.ts) using the the `express-jwt` package that is the culprit spitting out the `UnauthorizedError`. And yeah, to me, it looks like all it needs configured is `JWKS_URL`. Any ideas why the middleware would behave differently between `/debug` and `/dashboard` @zepatrik ?

**Comment by aeneasr** [comment] 2020-10-11 18:06
Hey there, sorry to see you have troubles. It's hard to help in this scenario without a reproducible repository on GitHub because it's difficult to share all the context required for debugging.

I also checked out the [IAP guide](https://www.ory.sh/kratos/docs/guides/zero-trust-iap-proxy-identity-access-proxy/) from start and could not reproduce your issues.
